config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :rooms
  resources :messages
  root to: 'rooms#index'
  get "/load_more", to: "rooms#load_more"
  get "/load_more_unread", to: "rooms#load_more_unread_message"
  get "/request_to_room", to: "rooms#request_to_room"
  post "/access_user_to_room", to: "rooms#access_user_to_room"
  post "/kick_out_of_room", to: "rooms#kick_out_of_room"

  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  after_create_commit { MessageBroadcastJob.perform_later self }
  belongs_to :user
  belongs_to :room

  mount_uploader :image, ImageUploader
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
end

app/models/permission.rb
class Permission < ApplicationRecord
  belongs_to :user
  belongs_to :room

  enum pms: {owner: 1, user: 2}
  enum status: {requesting: 1, approved: 2}

  scope :except_owner, -> (uid){ where.not(user_id: uid)}
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :messages
  has_many :permissions
  has_many :unread_messages

  mount_uploader :image, ImageUploader
end

app/models/unread_message.rb
class UnreadMessage < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :messages
  has_many :rooms
  has_many :permissions
  has_many :unread_messages
  has_many :notifications
  # Ex:- scope :active, -> {where(:active => true)}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!

  def new
    @message = Message.new
  end

  def create
    return if params["message"]["content"].blank?

    @room = Room.find_by id: params["message"]["room_id"]
    @message = @room.messages.new message_params
    @message.user = current_user

    if @message.save
      unread_msg = UnreadMessage.find_or_create_by! user: current_user, room: @room

      unread_msg.update! seen_at: @message.created_at if unread_msg

      users_in_room = Permission.where(room: @room, status: :approved)
                                .except_owner(current_user.id)
                                .pluck(:user_id)

      p users_in_room
      users_in_room.each do |user_id|
        ActionCable.server.broadcast(
          "activity_#{user_id}_channel",
          [{room: {name: @room.name, id: @room.id}, user: current_user.name, content: @message.content}, "send_message"]
        )
      end

      respond_to do |format|
        format.js { render layout: false, content_type: "text/javascript" }
      end
    else
      render room_path(@room.id)
    end
  end

  private
  def message_params
    params.require(:message).permit :content, :image, :user_id, :room_id
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_room, only: %i(load_more load_more_unread_message)

  def index
    @rooms = Room.includes(:permissions).all
  end

  def new
    @room = current_user.rooms.new
  end

  def show
    @room = Room.find_by id: params[:id]
    unless check_permission(@room)
      redirect_to rooms_path
      return
    end
    um = UnreadMessage.find_by(user: current_user, room: @room)
    um = UnreadMessage.create! user: current_user, room: @room, seen_at: Time.zone.now unless um

    msgs = @room.messages.includes(:user).where("created_at >= ?", um.seen_at)

    @messages = if um && msgs.count >= 7
                  msgs.first(7)
                else
                  um.update! seen_at: Time.zone.now
                  @room.messages.includes(:user).last(7)
                end
    # @requests = Permission.where room: @room, status: :requesting
    @requests = @room.user == current_user ? @room.permissions.includes(:user).except_owner(current_user.id) : {}
  end

  def create
    @room = current_user.rooms.new room_params

    if @room.save
      Permission.create! user: current_user, room: @room, pms: :owner, status: :approved
      flash[:success] = "Room is created"
      redirect_to root_url
    else
      flash.now[:danger] = "Something wrong"
      render :new
    end
  end

  def load_more
    @m = @room.messages.where("id < ?", params["id_msg"]).last(5)
  end

  def load_more_unread_message
    @m = @room.messages.where("id > ?", params["id_msg"]).first(5)
    unread_msg = UnreadMessage.find_by user: current_user, room: @room

    unread_msg.update! seen_at: @m.last.created_at if unread_msg && @m.present?
  end

  def request_to_room
    Permission.create! user_id: params[:user], room_id: params[:room], pms: :user, status: :requesting
    # @pms = Permission.find_by user_id: params[:user], room_id: params[:room]
    @req_from_user = User.find_by id: params[:user]
    @room = Room.find_by id: params[:room]
    broadcast_noti @room.user.id, [ApplicationController.render(partial: "rooms/notification_req_to_owner", locals: {user: @req_from_user, room: @room}),"request_to_room", @room.id]
  end

  def access_user_to_room
    @room = Room.find_by id: params[:room], user: current_user
    return unless @room || @room.user == current_user

    @pms = Permission.find_by user_id: params[:user], room_id: params[:room], status: :requesting
    @pms.update! status: :approved
    broadcast_noti params[:user], [{name: @room.name, id: @room.id}, "access_user_to_room"]
  end

  def kick_out_of_room
    @room = Room.find_by id: params[:room], user: current_user
    return unless @room || @room.user == current_user

    @pms = Permission.find_by user_id: params[:user], room_id: params[:room]
    @pms.destroy
    broadcast_noti params[:user], [@room.name, "kick_out_of_room", root_path]
  end

  private

  def room_params
    params.require(:room).permit :name, :image
  end

  def check_permission room
    permission = Permission.find_by user: current_user, room: room, status: :approved
    return true if room.user == current_user || permission
    return false unless permission
  end

  def load_room
    @room = Room.find_by id: params["room_id"]
  end

  def broadcast_noti user_id, data
    ActionCable.server.broadcast(
      "activity_#{user_id}_channel",
      data
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
  def load_seen_at user_id, room_id
    um = UnreadMessage.find_by(user_id: user_id, room_id: room_id)
    return UnreadMessage.create(user_id: user_id, room_id: room_id, seen_at: Time.zone.now) unless um

    um
  end

  def count_unread_message room
    um = room.unread_messages.find_by user: current_user
    return 0 unless um && check_permission(room)

    Message.where("room_id = ? AND created_at > ?", room.id, um.seen_at).count
  end

  def check_permission room
    permission = Permission.find_by user: current_user, room: room, status: :approved
    return true if room.user == current_user || permission
    return false unless permission
  end

  def count_request room
    return 0 unless check_permission(room)

    room.permissions.where(room: room, status: :requesting).count
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoSocket</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
  </head>

  <body>
    <% if user_signed_in? %>
      <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "btn btn-danger btn-logout") %>
      <%= link_to('Back to list rooms', rooms_path, class: "btn btn-warning btn-logout") %>
      <span class = "btn btn-info btn-logout"><%= current_user.name%></span>
      <%# render "notifications/list_notification"%>
    <% end %>
    <%= yield %>
    <div class = "modal-request"></div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class = "message">
  <div class="outgoing_msg">
    <div class="sent_msg">
      <% if message.image? %>
        <%= image_tag(message.image_url, height: "120", width: "120") %>
        <%= link_to "Download", message.image.url, download: message.image.url %>
      <% end %>
      <% unless message.content.blank? %>
        <p data-msg-id = <%=message.id %>>
          <b>
            <%=message.user.name %> - <i><%= message.created_at.to_s(:short) %></i>
          </b>
          <br>
          <%= message.content %>
        </p>
      <% end %>
      <br>
    </div>
  </div>
</div>

app/views/messages/_message_other.html.erb
<div class = "message">
  <div class="incoming_msg">
    <div class="incoming_msg_img"> <img src="https://ptetutorials.com/images/user-profile.png" alt="sunil"> </div>
    <div class="received_msg">
      <div class="received_withd_msg">
        <%= image_tag(message.image_url, height: "120", width: "120") if message.image? %>
        <% unless message.content.blank? %>
        <p data-msg-id = <%=message.id %>>
          <b>
            <%= message.user.name %> - <i><%= message.created_at.to_s(:short) %></i>
            <%# load_seen_at(message.user.id, message.room.id).seen_at < message.created_at ? "*" : "" %>
          </b>
          <br>
          <%= message.content %>
        </p>
        <br>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/messages/create.js.erb
$("form").trigger("reset");
$("#preview").attr("src", "");

app/views/notifications/_list_notification.html.erb
<button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
  Request (1)
</button>
<div class="container">
  <div class="dropdown-menu">
    <a class="dropdown-item" href="#">Link 1</a>
    <a class="dropdown-item" href="#">Link 2</a>
    <a class="dropdown-item" href="#">Link 3</a>
  </div>
</div>

app/views/rooms/_button_req.html.erb
<% unless request.blank? %>
  <li class = "list-rq data-pms-<%= request.id %>">
    <div class="container">
      <div class="row">
        <b class = "name-user"><%=request.user.name%> &#8594;</b>
        <%= link_to("Accept &#10003;".html_safe, access_user_to_room_path(user: request.user.id, room: room.id), remote: true, class: "btn btn-info", method: :post) if request.requesting? %>
        <%= link_to("Kick &#10754;".html_safe, kick_out_of_room_path(user: request.user.id, room: room.id), remote: true, class: "btn btn-danger", method: :post) if request.approved?%>
      </div>
    </div>
  </li>
<%end%>

app/views/rooms/_list_messages.html.erb
<% messages.each do |message| %>
  <% if message.user_id == current_user.id%>
    <%= render "messages/message", message: message %>
  <% else %>
    <%= render "messages/message_other", message: message %>
  <% end %>
<% end %>

app/views/rooms/_notification_kicked.html.erb
<!-- The Modal -->
<div class="modal fade" id="myModal">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Notification</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <!-- Modal body -->
      <div class="modal-body">
        You have been kicked out of the room <b><%= room.name %></b>
      </div>

      <!-- Modal footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/rooms/_notification_req_to_owner.html.erb
<!-- Button to Open the Modal -->


<!-- The Modal -->
<div class="modal fade" id="myModal">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Request</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <!-- Modal body -->
      <div class="modal-body">
        You have a request from <b><%= user.name %></b> to join room <b><%= room.name %></b>
      </div>

      <!-- Modal footer -->
      <div class="modal-footer">
        <%= button_to "Accept for #{user.name}",
        access_user_to_room_path(user: user.id, room: room.id),
        remote: true,
        class: "btn btn-success"
         %>
        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/rooms/access_user_to_room.js.erb
$('.data-pms-<%= @pms.id %>').remove();
alert("Accepted for <%= @pms.user.name %>")
$('#myModal').modal('hide');

$('.list-req').prepend('<%= j(render "rooms/button_req", {request: @pms, room: @room}) %>');
requests = $(".badge-green.data-<%= @room.id%>");
requests.html(parseInt(requests.text()) - 1);

app/views/rooms/index.html.erb
<div class="container">
  <h2>List Room</h2>
  <div class="row">
    <% @rooms.each do |room| %>
      <div class="col-md-4">
        <div class="card">
          <div class="card-header text-white bold">
            <%= link_to "#{room.name}", room_path(room) %>
            <% if Permission.find_by user: current_user, room: room, status: :requesting %>
              <p class = "btn btn-warning req-<%=room.id%>">Requested</p>
            <% elsif Permission.find_by user: current_user, room: room, status: :approved %>
            <span class="badge-red data-<%=room.id%>"><%= count_unread_message(room)%></span>
            <% if room.user == current_user%>
              <span class="badge-green data-<%=room.id%>"><%= count_request(room)%></span>
            <%end%>
            <p class = "approved"></p>
            <% else %>
              <%= link_to "Request", request_to_room_path(user: current_user, room: room), class: "btn btn-info req-#{room.id}", remote: true %>
            <% end %>
          </div>
          <div class="card-footer bg-secondary text-white"><%= room.user.name %></div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<%= link_to "Create room", new_room_path, class: "btn btn-success" %>

app/views/rooms/kick_out_of_room.js.erb
$('.data-pms-<%= @pms.id %>').remove();
alert("Kicked <%= @pms.user.name %>")

app/views/rooms/load_more.js.erb
$('#messages').prepend('<%= j(render "rooms/list_messages", messages: @m) %>');

app/views/rooms/load_more_unread_message.js.erb
$('#messages').append('<%= j(render "rooms/list_messages", messages: @m) %>');

app/views/rooms/new.html.erb
<div class="container">
  <h2>Create Chat Room</h2>

  <%= form_for @room, html:{ class: "form-horizontal" } do |f| %>
    <div class="form-group">
      <%= f.label :name, class: "control-label col-sm-2" %>
      <div class="col-sm-10">
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <%= f.file_field :image %>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
</div>

app/views/rooms/request_to_room.js.erb
$(".req-<%=@room.id%>").removeClass("btn-info")
                        .addClass("btn-warning")
                        .html('Requested')

if (Notification.permission === 'granted') {
  var title = 'Notification'
  var body = 'Sent request to <%= @room.user.name %>.'
  var options = { body: body }
  new Notification(title, options)
}
$('.list-req').prepend('<%= j(render "rooms/button_req", {request: @pms, room: @room}) %>');

app/views/rooms/show.html.erb
<h1><%= @room.name %></h1>

<div class="messaging">
  <div class="inbox_msg">
    <div class="mesgs">
			<div class="msg_history" id="messages"
				current_user = <%= current_user.id %>
				room_id = <%= @room.id %>>
				<%= render "list_messages", messages: @messages%>
      </div>
			<div id = "typing-on"></div>
			<div class="type_msg">
				<div class="input_msg_write">
					<input id="user_id" name="user_id" type="hidden" value=<%= current_user.id %> />
					<%= form_for Message.new, url: messages_path, html:{ class: "form-horizontal" }, remote: true do |f| %>
						<%= f.file_field :image %>
						<%= f.text_field :content, "data-behavior" => "room_speaker", class: "write_msg form-control", placeholder: "Type a message" %>
						<%= f.hidden_field :room_id, value: @room.id %>
						<%= f.button type: :submit, class: "msg_send_btn", id: "submit-msg" do %>
						<i class='fa fa-paper-plane' aria-hidden='true'></i>
						<%end%>
					<% end %>
					<!-- <label for="file"></label><br />
					<img id="preview" width="50" height="50"/> -->
				</div>
			</div>
    </div>
  </div>
</div>

<div class="container">
<ul class = "list-req">
	<%@requests.each do |request| %>
		<%=render "rooms/button_req", {request: request, room: @room} %>
	<%end%>
</ul>
</div>

<script>
	$("#messages").animate({scrollTop:0},500);

	$("input[type=file]").on("change", function() {
		$("#preview").attr("src", URL.createObjectURL(this.files[0]));
	});

	$(function(){
		var yd=$('#messages');
		var lastScrollTop=Infinity;
		yd.scrollTop(yd.prop("scrollHeight") - yd.prop("clientHeight")).on('wheel',wheel);

		function loadMoreOnTop(){
			var msg_ids = $('p').map(function () {
				return $(this).attr("data-msg-id");
			});

			var min_id = Math.min.apply(Math, msg_ids);

			$.ajax({
				url: '<%=load_more_path%>',
				type: "GET",
				data: {"id_msg" : min_id, "room_id" : yd.attr("room_id")},
				success: function(response) {
				}
			});
		};

		function loadMoreOnBottom(){
			var msg_ids = $('p').map(function () {
				return $(this).attr("data-msg-id");
			});
			var max_id = Math.max.apply(Math, msg_ids);
			// console.log(max_id);
			$.ajax({
				url: '<%=load_more_unread_path%>',
				type: "GET",
				data: {"id_msg" : max_id, "room_id" : yd.attr("room_id")},
				success: function(response) {
				}
			});
		};
		var bot = 0;

		function wheel(){
			var st=$(this).scrollTop();
				if (st<=lastScrollTop && st<300){
					getMore();
				} else {
					bot++;
					if(bot == 1 || bot%12 == 0) loadMoreOnBottom();
				}
				lastScrollTop=st;
		};

		function getMore(){
			loadMoreOnTop();

			var lastHeight=yd.prop("scrollHeight");
			yd.scrollTop(yd.prop("scrollHeight")-lastHeight+4);
			yd.off("wheel",wheel);
			setTimeout(function(){
					yd.on('wheel',wheel);
			},300);
		};
	});
</script>